package com.example.charadas

data class Category(
    val name: String,
    val emoji: String,
    val words: List<String>
)

object Categories {

    private val peliculas = Category(
        name = "Películas",
        emoji = "🎬",
        words = listOf(
            "Titanic",
            "El Padrino",
            "Titanic",
            "Forrest Gump",
            "Matrix",
            "Avatar",
            "Gladiador",
            "Rocky",
            "Jurassic Park",
            "Volver al Futuro",
            "El Rey León",
            "Toy Story",
            "Buscando a Nemo",
            "Shrek",
            "Frozen",
            "Coco",
            "Up",
            "Los Increíbles",
            "Ratatouille",
            "Wall-E",
            "Intensamente",
            "Moana",
            "Encanto",
            "Aladdín",
            "La Bella y la Bestia",
            "La Sirenita",
            "El Libro de la Selva",
            "Mulán",
            "Pinocho",
            "Dumbo",
            "Bambi",
            "Cenicienta",
            "Blancanieves",
            "Harry Potter",
            "El Señor de los Anillos",
            "Star Wars",
            "Indiana Jones",
            "Tiburón",
            "E.T. el Extraterrestre",
            "Los Cazafantasmas",
            "Mi Pobre Angelito",
            "Matilda",
            "Karate Kid",
            "Top Gun",
            "Misión Imposible",
            "Rápidos y Furiosos",
            "Piratas del Caribe",
            "Batman",
            "Superman",
            "Spider-Man",
            "Los Vengadores",
            "Iron Man",
            "Thor",
            "Pantera Negra",
            "Capitán América",
            "Los Guardianes de la Galaxia",
            "Doctor Strange",
            "Hombres de Negro",
            "Terminator",
            "Depredador",
            "Alien",
            "Mad Max",
            "Duro de Matar",
            "John Wick",
            "El Exorcista",
            "Psicosis",
            "El Resplandor",
            "It",
            "Scream",
            "Chucky",
            "Annabelle",
            "El Conjuro",
            "Los Juegos del Hambre",
            "Crepúsculo",
            "Mamma Mia",
            "Grease",
            "Dirty Dancing",
            "Pretty Woman",
            "Ghost",
            "Cásate Conmigo",
            "Diario de una Pasión",
            "Cómo Perder a un Hombre en 10 Días",
            "Mean Girls",
            "Supercool",
            "Todo en Todas Partes al Mismo Tiempo",
            "Interestelar",
            "Inception",
            "El Caballero de la Noche",
            "Joker",
            "Coraje, el Perro Cobarde",
            "Madagascar",
            "Kung Fu Panda",
            "Cómo Entrenar a tu Dragón",
            "Mi Villano Favorito",
            "Los Minions",
            "La Era de Hielo",
            "Cars",
            "Monsters, Inc.",
            "Tarzán",
            "Hércules",
            "Rapunzel",
            "Valiente",
            "Oppenheimer",
            "Barbie",
            "Gran Turismo",
            "Spider-Man: Un Nuevo Universo",
            "El Gato con Botas",
            "Bob Esponja: La Película"
        ).distinct()
    )

    val all: List<Category> = listOf(peliculas)
}
